### ISSUE TITLE
IdentitySwitcher 9.2 erros when page going in edit mode

### ISSUE THREAD

**Issue by EPTamminga** [DNN-Connect/IdentitySwitcher#22]
Module builds, package is created, can be installated, but module fails on a DNN92 site when trying to put the module on a page. 

The Ajax/Panel construction must be removed and replaced by a modernized solution: use Angular for the module settings and especially for the dependency of role and user selection.

**Comment by EPTamminga** [comment]
'
`


Cannot unregister UpdatePanel with ID 'UpdatePanel1' since it was not registered with the ScriptManager. This might occur if the UpdatePanel was removed from the control tree and later added again, which is not supported.
Parameter name: updatePanel
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.ArgumentException: Cannot unregister UpdatePanel with ID 'UpdatePanel1' since it was not registered with the ScriptManager. This might occur if the UpdatePanel was removed from the control tree and later added again, which is not supported.
Parameter name: updatePanel

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[ArgumentException: Cannot unregister UpdatePanel with ID 'UpdatePanel1' since it was not registered with the ScriptManager. This might occur if the UpdatePanel was removed from the control tree and later added again, which is not supported.
Parameter name: updatePanel]
   System.Web.UI.PageRequestManager.UnregisterUpdatePanel(UpdatePanel updatePanel) +214
   System.Web.UI.UpdatePanel.OnUnload(EventArgs e) +62
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +378
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Control.UnloadRecursive(Boolean dispose) +254
   System.Web.UI.Page.UnloadRecursive(Boolean dispose) +23
   System.Web.UI.Page.ProcessRequestCleanup() +69
   System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +348
   System.Web.UI.Page.ProcessRequest() +75
   System.Web.UI.Page.ProcessRequest(HttpContext context) +105
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +866
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +213
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +91


Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3056.0

**Comment by Mark-89** [comment]
Overkillingly solved this by implementing an angular front end.
