### ISSUE TITLE
Compiled installable module

### ISSUE THREAD

**Issue by DNNhost** [DNN-Connect/IdentitySwitcher#39]
I work on a mac ... need a installable module ?

**Comment by EPTamminga** [comment]
This is for DNN CMS installations. 
So you need a DNN installation,  this is a 'normal' DNN extension (module).

**Comment by DNNhost** [comment]
ok    could not find .zip or  release ?

**Comment by EPTamminga** [comment]
This version is still ‘under development’. 
This new version is based on the original version of ErikVB. You will find an installatble version here: 
https://github.com/erikvb/Dnn.IdentitySwitcher

**Comment by EPTamminga** [comment]
Release version is available
